server:
  port: 8080

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-prueba
          uri: http://localhost:8081/
          predicates:
            - Path=/pruebas/**,/auth/**

        - id: ms-prueba-2
          uri: http://localhost:8082/
          predicates:
            - Path=/pruebas2/**
          filters:
            - AuthenticationFilter

#        - id:
#          uri: lb://
#          predicates:
#            - Path=
#          filters:
#            -

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        #        include: "*"
        include: gateway

jwt:
  secret: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"

info:
  app:
    name: ${spring.application.name}