server:
  port: ${PORT:${SERVER_PORT:8080}}

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
      discovery:
        locator:
          enabled: true
#      routes:
#        - id:
#          uri: lb://
#          predicates:
#            - Path=
#          filters:
#            -

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        #        include: "*"
        include: gateway

#jwt:
#  secret: ""

info:
  app:
    name: ${spring.application.name}