server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userslogin?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

management:
  endpoints:
    web:
      exposure:
        include: info
  info:
    env:
      enabled: true
    app:
      name: ms-prueba
      version: 1.0.0
      description: Microservicio Prueba

jwt:
  secret: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"

info:
  app:
    name: ${spring.application.name}