server:
  port: ${PORT:8888}

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mraspa/base.git
#          username: ${gitUser}
#          password: ${gitToken}
          default-label: security
          force-pull: true
          search-paths: Config-Data