server:
  port: ${PORT:8888}

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mraspa/base/tree/main
#          username: ${gitUser}
#          password: ${gitToken}
          default-label: config-server
          force-pull: true
          search-paths: Config-Data

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka